"""initial telemetry persistence

Revision ID: 2e8fd5cfdd89
Revises: 
Create Date: 2026-09-15 13:36:34.914634
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2e8fd5cfdd89'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('identity_key', sa.String(length=255), nullable=False),
    sa.Column('simulator', sa.String(length=128), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('make', sa.String(length=128), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('car_class', sa.String(length=128), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity_key')
    )
    op.create_table('data_sources',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('simulator', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=128), nullable=True),
    sa.Column('dataset_name', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('revision', sa.String(length=128), nullable=True),
    sa.Column('license', sa.String(length=128), nullable=True),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('model_versions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=128), nullable=False),
    sa.Column('model_type', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('artifact_uri', sa.Text(), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('source_revisions', sa.JSON(), nullable=False),
    sa.Column('feature_definition', sa.JSON(), nullable=False),
    sa.Column('compatibility', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_model_name_version')
    )
    op.create_table('tracks',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('identity_key', sa.String(length=255), nullable=False),
    sa.Column('simulator', sa.String(length=128), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('circuit', sa.String(length=255), nullable=False),
    sa.Column('layout', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('length_m', sa.Float(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity_key')
    )
    op.create_table('import_runs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('data_source_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('import_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('rows_seen', sa.BigInteger(), nullable=False),
    sa.Column('rows_inserted', sa.BigInteger(), nullable=False),
    sa.Column('rows_updated', sa.BigInteger(), nullable=False),
    sa.Column('quality_report', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_source_id', 'import_key', name='uq_import_source_key')
    )
    op.create_index(op.f('ix_import_runs_data_source_id'), 'import_runs', ['data_source_id'], unique=False)
    op.create_table('model_metrics',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('model_version_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('split', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_version_id', 'split', 'name', name='uq_metric_model_split_name')
    )
    op.create_table('sessions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('data_source_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('simulator', sa.String(length=128), nullable=False),
    sa.Column('track_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('car_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sampling_hz', sa.Float(), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_source_id', 'external_id', name='uq_session_source_external')
    )
    op.create_index(op.f('ix_sessions_car_id'), 'sessions', ['car_id'], unique=False)
    op.create_index(op.f('ix_sessions_data_source_id'), 'sessions', ['data_source_id'], unique=False)
    op.create_index('ix_sessions_track_car', 'sessions', ['track_id', 'car_id'], unique=False)
    op.create_index(op.f('ix_sessions_track_id'), 'sessions', ['track_id'], unique=False)
    op.create_table('analysis_runs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('analysis_version', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('quality_report', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laps',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('source_lap_key', sa.String(length=255), nullable=False),
    sa.Column('started_native_ns', sa.BigInteger(), nullable=True),
    sa.Column('ended_native_ns', sa.BigInteger(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('quality', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'source_lap_key', name='uq_lap_session_source_key')
    )
    op.create_index('ix_laps_session_number', 'laps', ['session_id', 'lap_number'], unique=False)
    op.create_table('conditions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('lap_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('origin', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lap_id'], ['laps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('findings',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('analysis_run_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('lap_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('finding_key', sa.String(length=255), nullable=False),
    sa.Column('detector', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('section_key', sa.String(length=128), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lap_id'], ['laps.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_run_id', 'finding_key', name='uq_finding_run_key')
    )
    op.create_table('prediction_profiles',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('model_version_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('session_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('lap_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('profile_key', sa.String(length=255), nullable=False),
    sa.Column('section_key', sa.String(length=128), nullable=True),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lap_id'], ['laps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_version_id', 'profile_key', name='uq_prediction_model_key')
    )
    op.create_index('ix_prediction_lap_section', 'prediction_profiles', ['lap_id', 'section_key'], unique=False)
    op.create_table('raw_telemetry_samples',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('data_source_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('session_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('lap_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('source_sample_key', sa.String(length=255), nullable=False),
    sa.Column('native_timestamp_ns', sa.BigInteger(), nullable=False),
    sa.Column('sample_index', sa.Integer(), nullable=False),
    sa.Column('simulator', sa.String(length=128), nullable=False),
    sa.Column('position_x_m', sa.Float(), nullable=True),
    sa.Column('position_y_m', sa.Float(), nullable=True),
    sa.Column('position_z_m', sa.Float(), nullable=True),
    sa.Column('speed_mps', sa.Float(), nullable=True),
    sa.Column('throttle', sa.Float(), nullable=True),
    sa.Column('brake', sa.Float(), nullable=True),
    sa.Column('clutch', sa.Float(), nullable=True),
    sa.Column('steering', sa.Float(), nullable=True),
    sa.Column('gear', sa.Integer(), nullable=True),
    sa.Column('engine_rpm', sa.Float(), nullable=True),
    sa.Column('heading_rad', sa.Float(), nullable=True),
    sa.Column('lap_progress', sa.Float(), nullable=True),
    sa.Column('completed_laps', sa.Integer(), nullable=True),
    sa.Column('longitudinal_accel_mps2', sa.Float(), nullable=True),
    sa.Column('lateral_accel_mps2', sa.Float(), nullable=True),
    sa.Column('yaw_rate_rad_s', sa.Float(), nullable=True),
    sa.Column('power_w', sa.Float(), nullable=True),
    sa.Column('torque_nm', sa.Float(), nullable=True),
    sa.Column('boost_bar', sa.Float(), nullable=True),
    sa.Column('additional_fields', sa.JSON(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lap_id'], ['laps.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_source_id', 'source_sample_key', name='uq_raw_source_sample')
    )
    op.create_index('ix_raw_lap_sample', 'raw_telemetry_samples', ['lap_id', 'sample_index'], unique=False)
    op.create_index('ix_raw_session_lap_time', 'raw_telemetry_samples', ['session_id', 'lap_id', 'native_timestamp_ns'], unique=False)
    op.create_table('processed_telemetry_samples',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('lap_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('raw_sample_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('processing_version', sa.String(length=128), nullable=False),
    sa.Column('sample_index', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('elapsed_s', sa.Float(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('speed_mps', sa.Float(), nullable=True),
    sa.Column('throttle', sa.Float(), nullable=True),
    sa.Column('brake', sa.Float(), nullable=True),
    sa.Column('steering', sa.Float(), nullable=True),
    sa.Column('gear', sa.Integer(), nullable=True),
    sa.Column('engine_rpm', sa.Float(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['lap_id'], ['laps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_sample_id'], ['raw_telemetry_samples.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lap_id', 'processing_version', 'sample_index', name='uq_processed_lap_version_sample')
    )
    op.create_index('ix_processed_lap_progress', 'processed_telemetry_samples', ['lap_id', 'progress'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('analysis_run_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('finding_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('lap_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('model_version_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('section_key', sa.String(length=128), nullable=True),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('driver_baseline', sa.JSON(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lap_id'], ['laps.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendation_outcomes',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('recommendation_id', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendation_ratings',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('recommendation_id', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.String(length=64), nullable=False),
    sa.Column('helpful', sa.Boolean(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendation_ratings')
    op.drop_table('recommendation_outcomes')
    op.drop_table('recommendations')
    op.drop_index('ix_processed_lap_progress', table_name='processed_telemetry_samples')
    op.drop_table('processed_telemetry_samples')
    op.drop_index('ix_raw_session_lap_time', table_name='raw_telemetry_samples')
    op.drop_index('ix_raw_lap_sample', table_name='raw_telemetry_samples')
    op.drop_table('raw_telemetry_samples')
    op.drop_index('ix_prediction_lap_section', table_name='prediction_profiles')
    op.drop_table('prediction_profiles')
    op.drop_table('findings')
    op.drop_table('conditions')
    op.drop_index('ix_laps_session_number', table_name='laps')
    op.drop_table('laps')
    op.drop_table('analysis_runs')
    op.drop_index(op.f('ix_sessions_track_id'), table_name='sessions')
    op.drop_index('ix_sessions_track_car', table_name='sessions')
    op.drop_index(op.f('ix_sessions_data_source_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_car_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('model_metrics')
    op.drop_index(op.f('ix_import_runs_data_source_id'), table_name='import_runs')
    op.drop_table('import_runs')
    op.drop_table('tracks')
    op.drop_table('model_versions')
    op.drop_table('data_sources')
    op.drop_table('cars')
    # ### end Alembic commands ###
