"""add datastore session analysis fields

Revision ID: 46bbf8ada43a
Revises: 2e8fd5cfdd89
Create Date: 2026-09-15 13:48:54.815858
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '46bbf8ada43a'
down_revision: Union[str, None] = '2e8fd5cfdd89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'analysis_runs',
        sa.Column('result_payload', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    )
    op.add_column('sessions', sa.Column('display_name', sa.String(length=255), nullable=True))
    op.add_column('sessions', sa.Column('notes', sa.Text(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'notes')
    op.drop_column('sessions', 'display_name')
    op.drop_column('analysis_runs', 'result_payload')
    # ### end Alembic commands ###
